# Generated by Django 5.0.1 on 2024-01-09 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apartment',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=52, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='entrance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='floor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='house_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[
                django.core.validators.RegexValidator(
                    regex='^((\\+\\d{,4})[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')],
                                   verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, max_length=52, null=True, verbose_name='Область'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_name',
            field=models.CharField(blank=True, max_length=52, null=True, verbose_name='Название улицы'),
        ),
    ]
