# Generated by Django 5.0.1 on 2024-01-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_customuser_apartment_alter_customuser_entrance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='apartment',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=52, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='entrance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='floor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='house_number',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post_code',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, max_length=52, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street_name',
            field=models.CharField(blank=True, max_length=52, null=True, verbose_name='Название улицы'),
        ),
    ]
