# Generated by Django 5.0.1 on 2024-01-09 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=52, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('М', 'Мужское'), ('Ж', 'Женское')], default='М', max_length=1,
                                           verbose_name='Пол')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52, verbose_name='Имя')),
                ('surname', models.CharField(max_length=52, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=52, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=16, unique=True, validators=[
                    django.core.validators.RegexValidator(
                        regex='^((\\+\\d{,4})[\\- ]?)?(\\(?\\d{3}\\)?[\\- ]?)?[\\d\\- ]{7,10}$')],
                                           verbose_name='Номер телефона')),
                ('region', models.CharField(max_length=52, verbose_name='Область')),
                ('city', models.CharField(max_length=52, verbose_name='Город')),
                ('street_name', models.CharField(max_length=52, verbose_name='Название улицы')),
                ('house_number', models.IntegerField(default=0, verbose_name='Номер дома')),
                ('entrance', models.IntegerField(default=0, verbose_name='Подъезд')),
                ('floor', models.IntegerField(default=0, verbose_name='Этаж')),
                ('apartment', models.IntegerField(default=0, verbose_name='Номер квартиры')),
                ('post_code', models.IntegerField(default=0, verbose_name='Почтовый индекс')),
                ('comment', models.TextField(max_length=300, verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('status', models.CharField(
                    choices=[('О', 'Оплачен'), ('С', 'Собирается'), ('От', 'Отправлен'), ('В', 'В пути'),
                             ('Ж', 'Ждет получения'), ('П', 'Получен')], default='О', max_length=2,
                    verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=56, verbose_name='Название')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('size',
                 models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'ExtraLarge')],
                                  default='S', max_length=2, verbose_name='Размер')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('product_description', models.TextField(verbose_name='Описание товара')),
                ('model_description', models.TextField(verbose_name='Описание модели')),
                ('delivery_description', models.TextField(verbose_name='Описание доставки')),
                ('vendor_code', models.CharField(max_length=52, verbose_name='Артикул')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
            ],
        ),
    ]
