# Generated by Django 5.0.1 on 2024-01-09 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                    verbose_name='Заказчик'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category',
                                    verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.gender', verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='main.product', verbose_name='Товары'),
        ),
    ]
