# Generated by Django 5.0.1 on 2024-01-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_alter_order_apartment_alter_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='apartment',
            field=models.IntegerField(default=0, verbose_name='Номер квартиры'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=52, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='order',
            name='entrance',
            field=models.IntegerField(default=0, verbose_name='Подъезд'),
        ),
        migrations.AlterField(
            model_name='order',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house_number',
            field=models.IntegerField(default=0, verbose_name='Номер дома'),
        ),
        migrations.AlterField(
            model_name='order',
            name='post_code',
            field=models.IntegerField(default=0, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(max_length=52, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street_name',
            field=models.CharField(max_length=52, verbose_name='Название улицы'),
        ),
    ]
