# Generated by Django 5.0.1 on 2024-01-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0007_alter_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужское'), ('Ж', 'Женское')], default='М', max_length=1,
                                   verbose_name='Пол'),
        ),
    ]
