# Generated by Django 5.0.1 on 2024-01-11 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0008_alter_product_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=123, max_length=100, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
