# Generated by Django 5.0.1 on 2024-01-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0009_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='URL slug'),
        ),
    ]
