# Generated by Django 5.0.1 on 2024-01-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
