# Generated by Django 5.0.1 on 2024-01-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_order_products_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
