# Generated by Django 5.0.1 on 2024-01-21 07:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_product_size_product_sizes_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes_choice',
        ),
        migrations.AddField(
            model_name='product',
            name='board',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=8), default=[['M', 30]], size=8),
            preserve_default=False,
        ),
    ]
