# Generated by Django 5.0.1 on 2024-01-21 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_product_sizes_choice_product_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='board',
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'ExtraLarge')], default='S', max_length=2, verbose_name='Размер')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='main.product')),
            ],
        ),
    ]
