# Generated by Django 5.0.1 on 2024-03-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_order_customer_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_code', models.CharField(max_length=15, verbose_name='Промо код')),
                ('change_type', models.CharField(choices=[('%', 'Процент от суммы'), ('-', 'Вычитание от суммы')], default='%', max_length=1, verbose_name='Тип изменения цены')),
                ('price_reduction', models.PositiveIntegerField(default=0, verbose_name='На сколько снижается цена')),
                ('activation_quantity', models.PositiveIntegerField(default=0, verbose_name='Количество активаций')),
            ],
        ),
    ]
