# Generated by Django 5.0.1 on 2024-03-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='order',
            name='total_sum',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Общая сумма заказа'),
        ),
    ]
